"""CoreForge — one-click standalone HTML report.

Bundles the current configuration, the last eigenvalue solution and (if
present) the fuel-cycle results into a single self-contained HTML file
(plotly figures via CDN) — ready to attach to a project report or open
on any machine.
"""
import numpy as np

import plots
import presets
import runner

VERSION = "8.3"

_CSS = """
body{font-family:system-ui,-apple-system,'Segoe UI',sans-serif;
     max-width:1080px;margin:2em auto;padding:0 1em;color:#0b0b0b}
h1{border-bottom:3px solid #2a78d6;padding-bottom:.2em}
h2{color:#1c5cab;margin-top:1.6em}
table{border-collapse:collapse;margin:.8em 0}
td,th{border:1px solid #e1e0d9;padding:.35em .8em;font-size:.92em}
th{background:#f4f4f1;text-align:left}
.metric{display:inline-block;margin:.4em 1.2em .4em 0}
.metric b{font-size:1.5em;display:block}
.note{background:#fff8e6;border-left:4px solid #eda100;padding:.6em 1em;
      font-size:.9em}
.qawarn{background:#fdeceb;border-left:4px solid #d03b3b;padding:.7em 1em;
      font-size:.92em;font-weight:600;color:#7a1f1f}
.fig{margin:1em 0}
"""


def _fig(fig):
    return ('<div class="fig">' +
            fig.to_html(full_html=False, include_plotlyjs=False) + '</div>')


def _metrics(pairs):
    return "".join(f'<div class="metric"><b>{v}</b>{k}</div>'
                   for k, v in pairs)


def build_html(cfg, title, ref_keff=None, result=None, burn=None,
               power_MW=None, fuel_height_cm=200.0, ref_note=None,
               eqfits=None, th=None):
    """Return a standalone HTML report string.

    power_MW : if given, adds an 'Operating point' section with absolute
               units (power density W/cm3, flux n/cm2/s, assembly MW).
    fuel_height_cm : active fuel height used for the 2-D fuel volume
               (ignored for 3-D cores, where the height is geometric).
    ref_note : QA message shown when a benchmark reference comparison
               was suppressed (modified configuration).
    eqfits   : list of inverse-designer records (one per attached
               equivalent fuel): dict(name, target=material-dict,
               enrich, ppm, residuals, note)."""
    H = ['<!DOCTYPE html><html><head><meta charset="utf-8">',
         f"<title>CoreForge report — {title}</title>",
         '<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>',
         f"<style>{_CSS}</style></head><body>",
         f"<h1>⚛️ CoreForge report — {title}</h1>",
         "<p>2-D/3-D multigroup neutron diffusion · Fortran red-black SOR "
         f"engine (OpenMP) · report generated by CoreForge v{VERSION}</p>"]

    nby = len(cfg["blocks"])
    nbx = len(cfg["blocks"][0])
    dim = "3-D" if cfg.get("axial") else "2-D"
    H.append("<h2>Configuration</h2><table>")
    rows = [("core", title), ("model", dim),
            ("lattice", f"{nbx} × {nby} blocks · pitch {cfg['pitch']} cm"),
            ("mesh (radial)", f"{nbx*cfg['div']} × {nby*cfg['div']} cells "
                              f"(Δ = {cfg['pitch']/cfg['div']:.3f} cm)"),
            ("energy groups", cfg["ng"]),
            ("materials", ", ".join(m["name"] for m in cfg["materials"])),
            ("BC", " / ".join(cfg["bc"])),
            ("vacuum γ", cfg.get("gamma", 0.4692))]
    if cfg.get("axial"):
        ax = cfg["axial"]
        divz = int(ax.get("divz", 1))
        nzl = sum(int(z["layers"]) for z in ax["zones"]) * divz
        rows.insert(4, ("axial", f"{nzl} layers × {ax['dz']/divz:.3g} cm — " +
                        "; ".join(f"{z['label']} ({z['layers']*divz})"
                                  for z in ax["zones"])))
    for k, v in rows:
        H.append(f"<tr><th>{k}</th><td>{v}</td></tr>")
    H.append("</table>")

    H.append("<h2>Engine validation (fixed reference suite)</h2><table>")
    H.append("<tr><th>case</th><th>CoreForge</th><th>reference</th>"
             "<th>diff</th></tr>")
    for row in [("Homogeneous k∞ (analytic)", "1.0857142", "1.0857143",
                 "−0.0 pcm"),
                ("Bare square 1-group (analytic B²)", "1.2610188",
                 "1.2610203", "−0.1 pcm"),
                ("IAEA-2D PWR, h=1 cm", "1.0295785", "1.02959", "−1.1 pcm"),
                ("IAEA-3D PWR (full x-y-z, h=2, dz=4)", "1.0289590",
                 "1.02903", "−6.7 pcm"),
                ("C5G7 MOX pin-cell diffusion demo, h=0.63",
                 "1.1863920", "1.18655 (MCNP transport)", "−11 pcm")]:
        H.append("<tr><td>" + "</td><td>".join(row) + "</td></tr>")
    H.append("</table>")

    if result is not None:
        k = result["keff"]
        H.append("<h2>Eigenvalue solution</h2>")
        pairs = [("k_eff", f"{k:.6f}"),
                 ("reactivity", f"{runner.rho_pcm(k):+,.0f} pcm"),
                 ("F_q (cell)", f"{result['fxy']:.3f}"),
                 ("outer iterations", result["outers"]),
                 ("solve time", f"{result['time_s']:.2f} s")]
        if ref_keff:
            pairs.insert(2, ("Δ vs reference",
                             f"{runner.rho_pcm(k)-runner.rho_pcm(ref_keff):+.1f} pcm"))
        if result.get("nz", 1) > 1:
            pairs.append(("F_z (axial)", f"{result['fz']:.3f}"))
        H.append(_metrics(pairs))
        if ref_note:
            H.append('<div class="note"><b>⚠️ QA — reference '
                     'comparison suppressed.</b> ' + ref_note + '</div>')
        fuel_ids = runner.fissile_ids(cfg["materials"])
        fuelmask = np.isin(result["mat_fine"], fuel_ids)
        H.append(_fig(plots.material_map_fig(
            result["mat_fine"], cfg["materials"], result["x"], result["y"],
            title="Core layout (radial)")))
        H.append(_fig(plots.power_fig(result["power"], fuelmask,
                                      result["x"], result["y"])))
        for g in range(cfg["ng"]):
            H.append(_fig(plots.field_fig(
                result["phi"][g], result["x"], result["y"],
                title=f"Flux — group {g+1}" +
                      (" (axial average)" if result.get("nz", 1) > 1 else ""),
                ramp=plots.GROUP_RAMPS[g % len(plots.GROUP_RAMPS)])))
        bp = runner.block_powers(result, cfg)
        H.append(_fig(plots.block_power_fig(bp, cfg["pitch"])))
        if result.get("nz", 1) > 1:
            H.append(_fig(plots.traverse_fig(
                result["z"], [("axial power", result["axial_power"])],
                title="Axial power profile", xlabel="z [cm]",
                ylabel="P/P̄ (layer)")))

        # ---- operating point: absolute units --------------------------
        if power_MW:
            if result.get("nz", 1) > 1:
                dzf = (result["z"][1] - result["z"][0]
                       if result["nz"] > 1 else 1.0)
                nfuel = int((result["power3d"] > 1e-12).sum())
                Vf = nfuel * result["dx"] * result["dx"] * dzf
                hnote = "fuel height from the 3-D geometry"
            else:
                Vf = (int(fuelmask.sum()) * result["dx"] * result["dx"]
                      * fuel_height_cm)
                hnote = f"assumed active height {fuel_height_cm:.0f} cm"
            q_avg = power_MW * 1e6 / Vf
            q_peak = q_avg * result["fxy"]
            # S = q_avg/kappa from total fission-rate conservation, applied
            # uniformly to every group (nu is already inside nuSf — no
            # separate nu-bar factor). Verified: reproduces the target
            # power to 4 significant digits on a 1-group test case.
            KAPPA = 3.204e-11
            s_flux = q_avg / KAPPA
            phi_pk = [float(result["phi"][g].max()) * s_flux
                      for g in range(cfg["ng"])]
            nfb = int(np.isfinite(bp).sum())
            H.append("<h2>Operating point — absolute units</h2>")
            H.append(_metrics([
                ("core thermal power", f"{power_MW:.0f} MW"),
                ("fuel volume", f"{Vf/1e6:.2f} m³"),
                ("avg power density", f"{q_avg:.1f} W/cm³"),
                ("peak power density", f"{q_peak:.1f} W/cm³"),
                ("peak thermal flux", f"{phi_pk[-1]:.2e} n/cm²·s"),
                ("peak fast flux", f"{phi_pk[0]:.2e} n/cm²·s"),
                ("avg assembly power", f"{power_MW/nfb:.2f} MW"),
                ("hottest assembly",
                 f"{np.nanmax(bp)*power_MW/nfb:.2f} MW")]))
            H.append(f'<p style="font-size:.85em;color:#52514e">'
                     f'q‴ = P/V_fuel ({hnote}); flux scale S = q‴/κ '
                     f'(κ = 200 MeV/fission) from total fission-rate '
                     f'conservation, applied uniformly to every group. '
                     f'Typical PWR bands: q‴ ~ 50–110 W/cm³, thermal flux '
                     f'~ 3–6·10¹³ n/cm²·s.</p>')

        # ---- neutron balance ------------------------------------------
        if "balance" in result:
            H.append("<h2>Neutron balance</h2><table><tr>" +
                     "".join(f"<th>{c}</th>"
                             for c in result["balance"]["columns"]) +
                     "</tr>")
            for row in result["balance"]["rows"]:
                H.append("<tr><td>" + "</td><td>".join(
                    f"{v:.4e}" if isinstance(v, float) else str(int(v))
                    for v in row) + "</td></tr>")
            H.append("</table>")

        # ---- QA / traceability -----------------------------------------
        fp = presets.fingerprint_of(cfg)
        if ref_keff:
            refstat = "VALID — pristine benchmark configuration"
        elif ref_note:
            refstat = "INVALIDATED — configuration modified after load"
        else:
            refstat = "none (user-defined core)"
        H.append("<h2>QA &amp; traceability</h2><table>")
        for kk, vv in [
                ("engine convergence",
                 "converged" if result.get("converged") else
                 "⚠️ NOT converged"),
                ("tolerances", f"k: {cfg.get('tolk', 1e-7):.1e} · "
                               f"source: {cfg.get('tols', 1e-5):.1e}"),
                ("SOR ω / inner sweeps",
                 f"{cfg.get('omega', 1.6)} / {cfg.get('ninner', 4)}"),
                ("physics fingerprint", f"<code>{fp}</code>"),
                ("benchmark reference status", refstat),
                ("code version", f"CoreForge v{VERSION}")]:
            H.append(f"<tr><th>{kk}</th><td>{vv}</td></tr>")
        H.append("</table>")

        if not ref_keff and abs(runner.rho_pcm(k)) > 500:
            H.append('<p style="font-size:.85em;color:#52514e">Note: the '
                     'excess reactivity corresponds to the AS-MODELLED '
                     'state (e.g. fresh, unborated fuel); in operation it '
                     'would be held down by soluble boron / burnable '
                     'absorbers — see the critical-boron and burnup '
                     'tools.</p>')

    # ---- thermal-hydraulics ---------------------------------------------
    if th is not None:
        a, hch = th["avg"], th["hot"]
        H.append("<h2>Thermal-hydraulics — closed-channel steady "
                 "state</h2>")
        H.append(_metrics([
            ("outlet T (avg / hot)",
             f"{a['T_out']:.1f} / {hch['T_out']:.1f} °C"),
            ("max clad surface (hot)", f"{hch['T_clad_max']:.1f} °C"),
            ("max fuel centreline (hot)", f"{hch['T_fuel_max']:.0f} °C"),
            ("saturation margin (hot)", f"{hch['sat_margin']:+.1f} K"),
            ("core ΔP (friction)", f"{a['dP_kPa']:.1f} kPa"),
            ("coolant velocity", f"{a['v_cool']:.2f} m/s"),
            ("hot-assembly F_ΔH", f"{th['F_dh']:.3f}"),
            ("energy closure", f"{th['Q_balance_MW']:.1f} MW")]))
        H.append(_fig(plots.traverse_fig(
            a["z"], [("avg channel", a["T_cool"]),
                     ("hot channel", hch["T_cool"]),
                     ("hot clad surface", hch["T_clad"])],
            title="Coolant & clad temperatures", xlabel="z [m]",
            ylabel="T [°C]")))
        H.append(_fig(plots.traverse_fig(
            a["z"], [("avg channel", a["T_fuel"]),
                     ("hot channel", hch["T_fuel"])],
            title="Fuel centreline temperature", xlabel="z [m]",
            ylabel="T [°C]")))
        H.append('<p style="font-size:.85em;color:#52514e">Single-phase '
                 'Dittus-Boelter model, constant properties at ~15.5 MPa '
                 '/ 310 °C; boiling/DNB not modelled (saturation margin '
                 'flags the limit). Energy conservation exact.</p>')

    # ---- inverse designer: equivalent-fuel reconstructions --------------
    if eqfits:
        H.append("<h2>Inverse designer — equivalent-fuel "
                 "reconstructions</h2>")
        H.append("<p>Each XS-only fuel below was matched to a physical "
                 "composition (enrichment + soluble boron) by sequential "
                 "bisection on the two constants the pin-cell model "
                 "controls monotonically: νΣf₂ → enrichment, Σa₂ → boron. "
                 "All remaining constants are reported as residuals — "
                 "never hidden.</p>")
        for fit in eqfits:
            tgt = fit["target"]
            eq = fit["material"]
            H.append(f"<h3>{fit['name']}</h3>")
            H.append(_metrics([
                ("equivalent enrichment", f"{fit['enrich']:.3f} w/o"),
                ("equivalent boron", f"{fit['ppm']:.0f} ppm"),
                ("k∞ target", f"{fit['residuals']['kinf_target']:.4f}"),
                ("k∞ equivalent", f"{fit['residuals']['kinf_eq']:.4f}")]))
            rows = [("D₁ [cm]", tgt["D"][0], eq["D"][0]),
                    ("D₂ [cm]", tgt["D"][1], eq["D"][1]),
                    ("Σa₁ [cm⁻¹]", tgt["Sa"][0], eq["Sa"][0]),
                    ("Σa₂ [cm⁻¹]", tgt["Sa"][1], eq["Sa"][1]),
                    ("νΣf₁ [cm⁻¹]", tgt["nuSf"][0], eq["nuSf"][0]),
                    ("νΣf₂ [cm⁻¹]", tgt["nuSf"][1], eq["nuSf"][1]),
                    ("Σ₁→₂ [cm⁻¹]", tgt["scat"][0][1], eq["scat"][0][1])]
            H.append("<table><tr><th>constant</th><th>target</th>"
                     "<th>equivalent</th><th>residual</th></tr>")
            for lbl, a, b in rows:
                d = (f"{100*(b-a)/a:+.2f}%" if a != 0 else "—")
                H.append(f"<tr><td>{lbl}</td><td>{a:.6g}</td>"
                         f"<td>{b:.6g}</td><td>{d}</td></tr>")
            H.append("</table>")
            H.append(_fig(plots.residual_fig(
                fit["residuals"],
                title=f"Residuals — {fit['name']}")))
            if fit.get("note"):
                H.append(f'<div class="note">{fit["note"]}</div>')
            if fit.get("reliable") is False:
                H.append(
                    '<div class="qawarn">⚠️ LOW RELIABILITY for '
                    f'reactivity-sensitive use — {fit["worst_key"]} '
                    f'residual is {fit["worst_pct"]:+.1f}% (threshold '
                    '±15%). The target likely represents a strongly '
                    'non-standard absorber (inserted control rod, '
                    'burnable poison) that a boron-water equivalent '
                    'cannot reproduce. k_eff / reactivity-worth results '
                    'that depend on this material are NOT reliable — '
                    'safe for depletion bookkeeping only.</div>')
        H.append('<div class="note"><b>Interpretation.</b> The matched '
                 'constants (νΣf₂, Σa₂) are exact by construction; the '
                 'k∞ difference reflects the generator\'s own fast-group '
                 'calibration. The equivalent is an approximate, clearly '
                 'labelled stand-in whose purpose is to make an XS-only '
                 'core <i>depletable</i> — not to reproduce the original '
                 'eigenvalue.</div>')

    if burn is not None:
        hist = burn["history"]
        H.append("<h2>Fuel cycle</h2>")
        pairs = [("cycle burnup", f"{hist[-1]['bu']:.1f} MWd/kgU"),
                 ("cycle length", f"{burn['efpd']:.0f} EFPD"),
                 ("xenon worth (BOC)",
                  f"{burn['maps']['xenon_worth_pcm']:+,.0f} pcm"),
                 ("EOC boron", f"{hist[-1]['ppm']:.0f} ppm"),
                 ("F_xy BOC→EOC",
                  f"{hist[0]['fxy']:.2f} → {hist[-1]['fxy']:.2f}")]
        if burn.get("eoc_reason"):
            pairs.insert(0, ("end of cycle", burn["eoc_reason"]))
        H.append(_metrics(pairs))
        bus = [h["bu"] for h in hist]
        H.append(_fig(plots.search_fig(
            list(zip(bus, [h["keff"] for h in hist])), 1.0,
            title="k_eff over the cycle", xlabel="burnup [MWd/kgU]")))
        H.append(_fig(plots.traverse_fig(
            bus, [("boron [ppm]", [h["ppm"] for h in hist])],
            title="Boron letdown curve", xlabel="burnup [MWd/kgU]",
            ylabel="boron [ppm]")))
        H.append(_fig(plots.block_power_fig(
            burn["bumap"], cfg["pitch"], title="EOC burnup map [MWd/kgU]",
            zmid=None, colorscale="Oranges", fmt=1, unit="BU")))
        H.append('<table><tr><th>BU [MWd/kgU]</th><th>EFPD</th>'
                 '<th>k_eff</th><th>boron [ppm]</th><th>F_xy</th></tr>')
        for h in hist:
            H.append(f"<tr><td>{h['bu']:.1f}</td><td>{h['efpd']:.0f}</td>"
                     f"<td>{h['keff']:.5f}</td><td>{h['ppm']:.0f}</td>"
                     f"<td>{h['fxy']:.3f}</td></tr>")
        H.append("</table>")

    H.append('<div class="note"><b>Model scope.</b> 2-D/3-D multigroup '
             'diffusion (assembly/pin-cell homogenised); Robin vacuum '
             'boundaries; depletion chain U-235/238 → Pu-239/240/241 with '
             'equilibrium Xe-135/Sm-149 and a calibrated lumped '
             'fission-product pair; frozen 2-group spectrum; no '
             'thermal-hydraulic/Doppler feedback. Fuel-designer cross '
             'sections are educational lattice physics — trends are '
             'physical, absolute values representative.</div>')
    H.append("</body></html>")
    return "\n".join(H)
