"""CoreForge — Python driver for the Fortran engine.

Writes the keyword input file, launches ``solver/coreforge``, parses the
summary and the field CSVs (2-D or 3-D), and provides the higher-level
reactor-physics tools (material-swap worth, criticality searches).

Only numpy is required here; the Streamlit app adds pandas/plotly on top.
"""
import copy
import os
import shutil
import subprocess
import tempfile
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
BC_CODE = {"vacuum": 0, "reflective": 1}


def ncpu():
    """CPU count that respects container/cgroup limits (Streamlit Cloud
    boxes report the host's cores via cpu_count but only a couple are
    actually schedulable)."""
    try:
        return len(os.sched_getaffinity(0)) or 1
    except AttributeError:          # non-Linux
        return os.cpu_count() or 1


# ----------------------------------------------------------------------
def build_engine():
    """One-shot engine build from source.  Used when only the source ships
    (e.g. Streamlit Community Cloud, where packages.txt installs gfortran).
    Tries ifx first (the development compiler), then gfortran.  Each call
    compiles in its own private temp directory (so concurrent sessions
    never share the object/module files or a half-written binary) and the
    finished binary is moved into place atomically.  Returns the path or
    None; the compiler log is written to solver/build.log either way."""
    sdir = os.path.join(HERE, "solver")
    src = os.path.join(sdir, "coreforge.f90")
    out = os.path.join(sdir, "coreforge")
    if not os.path.isfile(src):
        return None
    for fc, flags in (("ifx", ["-O3", "-qopenmp"]),
                      ("gfortran", ["-O3", "-fopenmp"])):
        if shutil.which(fc) is None:
            continue
        tdir = tempfile.mkdtemp(prefix="build-", dir=sdir)
        try:
            try:
                r = subprocess.run([fc, *flags, src, "-o", "coreforge"],
                                   cwd=tdir, capture_output=True, text=True,
                                   timeout=300)
                logtxt = (f"$ {fc} {' '.join(flags)} coreforge.f90\n"
                          f"{r.stdout}\n{r.stderr}\n")
                built = r.returncode == 0
            except subprocess.TimeoutExpired:
                logtxt = (f"$ {fc} {' '.join(flags)} coreforge.f90\n"
                          "compiler timed out after 300 s\n")
                built = False
            logf = os.path.join(tdir, "build.log")
            with open(logf, "w") as f:
                f.write(logtxt)
            os.replace(logf, os.path.join(sdir, "build.log"))
            tmp = os.path.join(tdir, "coreforge")
            if built and os.path.isfile(tmp):
                os.chmod(tmp, 0o755)
                os.replace(tmp, out)
                return out
        finally:
            shutil.rmtree(tdir, ignore_errors=True)
    return None


def engine_path(autobuild=True):
    for cand in ("coreforge", "coreforge.exe", "coreforge.out"):
        p = os.path.join(HERE, "solver", cand)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    return build_engine() if autobuild else None


def expand_blocks(blocks, div):
    """Block lattice (rows top-first) -> fine mesh map (rows top-first)."""
    a = np.asarray(blocks, dtype=int)
    return np.kron(a, np.ones((div, div), dtype=int))


def fissile_ids(materials):
    return [i + 1 for i, m in enumerate(materials)
            if any(v > 0 for v in m["nuSf"])]


def rho_pcm(k):
    return (k - 1.0) / k * 1e5


def auto_threads(cfg):
    """Thread count matched to problem size: the engine parallelises over
    mesh rows, so tiny meshes are FASTER on few threads (fork/barrier
    overhead dominates)."""
    rows = len(cfg["blocks"]) * cfg["div"]
    if cfg.get("axial"):
        nzl = sum(int(z["layers"]) for z in cfg["axial"]["zones"])
        rows *= max(1, nzl * int(cfg["axial"].get("divz", 1)))
    return max(1, min(ncpu(), rows // 12 + 1))


# ----------------------------------------------------------------------
def write_input(cfg):
    """cfg keys: ng, pitch, div, blocks, materials, bc (4 names for 2-D,
    6 for 3-D: W,E,S,N,Bottom,Top), gamma, optional omega/tolk/tols/
    ninner/maxout, and optional `axial` for 3-D:
      axial = dict(dz=..., divz=1, zones=[{label, layers, blocks}, ...])
    (zones bottom -> top; every zone's block lattice must have the same
    shape as cfg['blocks'])."""
    ng = cfg["ng"]
    axial = cfg.get("axial")
    fine = expand_blocks(cfg["blocks"], cfg["div"])
    nyf, nxf = fine.shape
    d = cfg["pitch"] / cfg["div"]
    L = []
    L.append(f"# CoreForge input — generated by runner.py")
    L.append(f"NG {ng}")
    L.append(f"NX {nxf}")
    L.append(f"NY {nyf}")
    if axial:
        divz = int(axial.get("divz", 1))
        nzl = sum(int(z["layers"]) for z in axial["zones"]) * divz
        L.append(f"NZ {nzl}")
        L.append(f"DZ {axial['dz']/divz:.10g}")
    L.append(f"DX {d:.10g}")
    L.append(f"DY {d:.10g}")
    L.append("BC " + " ".join(str(BC_CODE[b]) for b in cfg["bc"]))
    L.append(f"GAMMA {cfg.get('gamma', 0.4692):.10g}")
    for key in ("omega", "tolk", "tols", "ninner", "maxout"):
        if key in cfg and cfg[key] is not None:
            L.append(f"{key.upper()} {cfg[key]:.10g}" if isinstance(cfg[key], float)
                     else f"{key.upper()} {cfg[key]}")
    mats = cfg["materials"]
    L.append(f"NMAT {len(mats)}")
    for mid, m in enumerate(mats, start=1):
        L.append(f"MAT {mid}   # {m.get('name','')}")
        L.append("D    " + " ".join(f"{v:.10g}" for v in m["D"]))
        L.append("SA   " + " ".join(f"{v:.10g}" for v in m["Sa"]))
        L.append("NUSF " + " ".join(f"{v:.10g}" for v in m["nuSf"]))
        L.append("CHI  " + " ".join(f"{v:.10g}" for v in m["chi"]))
        L.append("SCAT")
        for gf in range(ng):
            L.append(" ".join(f"{m['scat'][gf][gt]:.10g}" for gt in range(ng)))
    if axial:
        divz = int(axial.get("divz", 1))
        l1 = 1
        for z in axial["zones"]:
            nl = int(z["layers"]) * divz
            zf = expand_blocks(z["blocks"], cfg["div"])
            if zf.shape != fine.shape:
                raise ValueError("all axial zones must share the radial "
                                 "lattice shape")
            L.append(f"MAP {l1} {l1+nl-1}   # {z.get('label','zone')}")
            for row in zf:
                L.append(" ".join(str(int(v)) for v in row))
            l1 += nl
    else:
        L.append("MAP")
        for row in fine:
            L.append(" ".join(str(int(v)) for v in row))
    return "\n".join(L) + "\n"


# ----------------------------------------------------------------------
def _parse_summary(stdout):
    out = {}
    bal, inbal = [], False
    for line in stdout.splitlines():
        s = line.strip()
        if s.startswith("BALANCE_BEGIN"):
            inbal = True
            continue
        if s.startswith("BALANCE_END"):
            inbal = False
            continue
        if inbal:
            bal.append(s)
            continue
        for key, cast in (("KEFF", float), ("FXY", float), ("DR", float),
                          ("TIME_S", float), ("OUTERS", int)):
            if s.startswith(key + " ") or s.startswith(key + "="):
                out[key.lower()] = cast(s.split("=")[1])
        if s.startswith("CONVERGED"):
            out["converged"] = "YES" in s
        if s.startswith("FXYLOC"):
            out["fxy_loc"] = tuple(int(v) for v in s.split("=")[1].split())
    if bal:
        hdr = bal[0].split(",")
        rows = [[float(v) for v in r.split(",")] for r in bal[1:]]
        out["balance"] = {"columns": hdr, "rows": rows}
    return out


def _display_zone(cfg):
    """Zone index used for the radial material display (most fissile)."""
    fids = set(fissile_ids(cfg["materials"]))
    best, bestn = 0, -1
    for zi, z in enumerate(cfg["axial"]["zones"]):
        n = sum(1 for row in z["blocks"] for v in row if v in fids)
        if n > bestn:
            best, bestn = zi, n
    return best


def _prune_runs(runs, keep=200):
    """Keep only the most recent `keep` run directories so a long-lived
    server (e.g. Streamlit Cloud) doesn't grow runs/ without bound."""
    try:
        dirs = [os.path.join(runs, d) for d in os.listdir(runs)]
        dirs = [d for d in dirs if os.path.isdir(d)]
        if len(dirs) <= keep:
            return
        dirs.sort(key=lambda d: os.path.getmtime(d))
        for d in dirs[:len(dirs) - keep]:
            shutil.rmtree(d, ignore_errors=True)
    except OSError:
        pass


def run_case(cfg, workdir=None, threads=None, timeout=1800):
    """Run one eigenvalue case. Returns a dict with keff, fxy, balance,
    flux, power, coordinates, log, workdir.  For 3-D cases (cfg['axial'])
    also phi3d (ng,nz,ny,nx), power3d, axial_power, z — while the 2-D
    fields phi/power hold the axial averages so every 2-D display works."""
    eng = engine_path()
    if eng is None:
        raise RuntimeError(
            "Engine not found and auto-build failed (see solver/build.log).\n"
            "Build it manually with one of:\n"
            "  ifx -O3 -qopenmp solver/coreforge.f90 -o solver/coreforge\n"
            "  gfortran -O3 -fopenmp solver/coreforge.f90 -o solver/coreforge")
    if workdir is None:
        # Streamlit serves every session from ONE process, so a pid+second
        # name collides across concurrent users (silently overwriting each
        # other's flux.csv/input.txt).  mkdtemp guarantees a unique dir.
        runs = os.path.join(HERE, "runs")
        os.makedirs(runs, exist_ok=True)
        _prune_runs(runs)
        workdir = tempfile.mkdtemp(prefix=time.strftime("%Y%m%d-%H%M%S-"),
                                   dir=runs)
    os.makedirs(workdir, exist_ok=True)
    text = write_input(cfg)
    with open(os.path.join(workdir, "input.txt"), "w") as f:
        f.write(text)

    env = dict(os.environ)
    env["OMP_NUM_THREADS"] = str(threads or auto_threads(cfg))
    try:
        proc = subprocess.run([eng, "input.txt"], cwd=workdir, env=env,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        raise RuntimeError(
            f"Engine timed out after {timeout} s — the mesh is likely too "
            "fine for this machine.  Reduce div/divz and try again.")
    if proc.returncode != 0:
        raise RuntimeError("Engine failed:\n" + proc.stderr + "\n" + proc.stdout[-2000:])

    res = _parse_summary(proc.stdout)
    res["log"] = proc.stdout
    res["input_text"] = text
    res["workdir"] = workdir
    with open(os.path.join(workdir, "run.log"), "w") as f:  # QA trail
        f.write(proc.stdout)
        if proc.stderr:
            f.write("\n--- stderr ---\n" + proc.stderr)

    fine = expand_blocks(cfg["blocks"], cfg["div"])
    nyf, nxf = fine.shape
    d = cfg["pitch"] / cfg["div"]
    axial = cfg.get("axial")
    if axial:
        divz = int(axial.get("divz", 1))
        nzf = sum(int(z["layers"]) for z in axial["zones"]) * divz
        dzf = axial["dz"] / divz
    else:
        nzf, dzf = 1, 1.0

    flux = np.genfromtxt(os.path.join(workdir, "flux.csv"),
                         delimiter=",", names=True)
    power = np.genfromtxt(os.path.join(workdir, "power.csv"),
                          delimiter=",", names=True)
    ng = cfg["ng"]
    # engine writes x fastest, then y (bottom-first), then z (bottom-first)
    phi3d = np.stack([flux[f"phi_g{g}"].reshape(nzf, nyf, nxf)
                      for g in range(1, ng + 1)])          # [g,z,y,x]
    pow3d = power["power_rel"].reshape(nzf, nyf, nxf)
    res["nz"] = nzf
    res["phi3d"] = phi3d
    res["power3d"] = pow3d
    res["phi"] = phi3d.mean(axis=1)                        # [g,y,x]
    res["power"] = pow3d.mean(axis=0)                      # [y,x]
    if axial:
        zone = axial["zones"][_display_zone(cfg)]
        res["mat_fine"] = np.flipud(expand_blocks(zone["blocks"], cfg["div"]))
        lp = pow3d.sum(axis=(1, 2))                        # per-layer power
        nzp = lp > 1e-12
        res["axial_power"] = np.where(nzp, lp / max(lp[nzp].mean(), 1e-30),
                                      0.0)
        res["z"] = (np.arange(nzf) + 0.5) * dzf
        res["fz"] = float(res["axial_power"].max()) if nzp.any() else 1.0
    else:
        res["mat_fine"] = np.flipud(fine)
    res["x"] = (np.arange(nxf) + 0.5) * d
    res["y"] = (np.arange(nyf) + 0.5) * d
    res["dx"] = d
    return res


# ----------------------------------------------------------------------
def block_powers(res, cfg):
    """Aggregate the fine power map back to the block lattice.
    Returns (nby,nbx) array, top-first, normalised to mean 1 over fuel
    blocks; non-fuel blocks are NaN."""
    div = cfg["div"]
    p = np.flipud(res["power"])                    # top-first
    nby, nbx = np.asarray(cfg["blocks"]).shape
    bp = p.reshape(nby, div, nbx, div).sum(axis=(1, 3))
    fuel = bp > 1e-12
    if fuel.any():
        bp = bp / bp[fuel].mean()
    out = np.where(fuel, bp, np.nan)
    return out


# ----------------------------------------------------------------------
def material_swap_worth(cfg, mat_a, mat_b, threads=None):
    """Reactivity worth of replacing material id mat_a by mat_b everywhere
    (including every axial zone in 3-D)."""
    base = run_case(cfg, threads=threads)
    cfg2 = copy.deepcopy(cfg)
    cfg2["blocks"] = [[mat_b if v == mat_a else v for v in row]
                      for row in cfg["blocks"]]
    if cfg2.get("axial"):
        for z in cfg2["axial"]["zones"]:
            z["blocks"] = [[mat_b if v == mat_a else v for v in row]
                           for row in z["blocks"]]
    pert = run_case(cfg2, threads=threads)
    k1, k2 = base["keff"], pert["keff"]
    return dict(k1=k1, k2=k2,
                rho1_pcm=rho_pcm(k1), rho2_pcm=rho_pcm(k2),
                worth_pcm=rho_pcm(k2) - rho_pcm(k1),
                base=base, pert=pert)


def critical_boron_search(cfg, target=1.0, tol_pcm=2.0, max_runs=25,
                          threads=None, callback=None):
    """Find the uniform soluble-boron concentration [ppm] that makes
    k_eff = target.  Every material carrying `designer` metadata (made by
    xslib) is rebuilt at the trial ppm; other materials stay untouched."""
    import xslib
    des = [i for i, m in enumerate(cfg["materials"]) if "designer" in m]
    if not des:
        raise ValueError("no designer materials in the core "
                         "(build fuels in the Fuel designer tab first)")

    def k_of(ppm):
        c = copy.deepcopy(cfg)
        for i in des:
            d = cfg["materials"][i]["designer"]
            nm = xslib.cell_from_N(d["N"], ppm, d["rho_mod"],
                                   d["r_fuel"], d["pitch"],
                                   enrich_label=d.get("enrich"))
            nm["name"] = cfg["materials"][i]["name"]
            c["materials"][i] = nm
        return run_case(c, threads=threads)["keff"]

    history = []

    def probe(ppm):
        k = k_of(ppm)
        history.append((ppm, k))
        if callback:
            callback(len(history), ppm, k)
        return k

    lo, hi = 0.0, 1000.0
    klo = probe(lo)
    if klo < target:
        return dict(history=history, ppm=0.0, k=klo, runs=len(history),
                    note="core is below target even at 0 ppm")
    khi = probe(hi)
    while khi > target and len(history) < max_runs:
        lo, klo = hi, khi
        hi *= 2.0
        if hi > 40000:
            raise RuntimeError("not reaching target even at 40000 ppm")
        khi = probe(hi)
    while len(history) < max_runs:
        mid = 0.5 * (lo + hi)
        k = probe(mid)
        if abs(rho_pcm(k) - rho_pcm(target)) < tol_pcm:
            return dict(history=history, ppm=mid, k=k, runs=len(history))
        if k > target:
            lo = mid
        else:
            hi = mid
    ppm, k = history[-1]
    return dict(history=history, ppm=ppm, k=k, runs=len(history))


def criticality_search(cfg, mat_ids, group=None, target=1.0,
                       tol_pcm=1.0, max_runs=25, threads=None, callback=None):
    """Find the uniform delta-Sigma_a (added to `group` of materials
    `mat_ids`) that makes k_eff = target. Bisection with automatic
    bracketing. Returns dict(history=[(dsa,k),...], dsa=..., k=...)."""
    ng = cfg["ng"]
    if group is None:
        group = ng
    gi = group - 1

    def k_of(dsa):
        c = copy.deepcopy(cfg)
        for mid in mat_ids:
            c["materials"][mid - 1]["Sa"][gi] += dsa
            if c["materials"][mid - 1]["Sa"][gi] <= 0:
                raise ValueError("Sigma_a became non-positive during search")
        r = run_case(c, threads=threads)
        return r["keff"]

    history = []

    def probe(dsa):
        k = k_of(dsa)
        history.append((dsa, k))
        if callback:
            callback(len(history), dsa, k)
        return k

    k0 = probe(0.0)
    if abs(rho_pcm(k0) - rho_pcm(target)) < tol_pcm:
        return dict(history=history, dsa=0.0, k=k0, runs=len(history))

    lo, hi = None, None
    if k0 > target:
        step = 0.5 * min(m["Sa"][gi] for m in
                         (cfg["materials"][i - 1] for i in mat_ids))
        step = max(step, 1e-4)
        d = step
        klo, dlo = k0, 0.0
        while len(history) < max_runs:
            k = probe(d)
            if k < target:
                lo, hi = dlo, d
                break
            dlo, klo = d, k
            d *= 2.0
        else:
            raise RuntimeError("could not bracket the critical point")
    else:
        samin = min(cfg["materials"][i - 1]["Sa"][gi] for i in mat_ids)
        d = -0.25 * samin
        dhi, khi = 0.0, k0
        while len(history) < max_runs:
            k = probe(d)
            if k > target:
                lo, hi = d, dhi
                break
            dhi, khi = d, k
            if abs(d) > 0.85 * samin:
                raise RuntimeError("critical point not reachable "
                                   "(Sigma_a would become negative)")
            d = max(d * 2.0, -0.85 * samin)
        else:
            raise RuntimeError("could not bracket the critical point")

    while len(history) < max_runs:
        mid = 0.5 * (lo + hi)
        k = probe(mid)
        if abs(rho_pcm(k) - rho_pcm(target)) < tol_pcm:
            return dict(history=history, dsa=mid, k=k, runs=len(history))
        if k > target:
            lo = mid
        else:
            hi = mid
    dsa, k = history[-1]
    return dict(history=history, dsa=dsa, k=k, runs=len(history))
